### ISSUE TITLE
Being able to customize the line/circle width

### ISSUE THREAD

**Issue by dogfootruler-kr** [prabhuignoto/react-chrono#168]
I would like to be able to customize the design of the line and circles (especially changing their size as we can change the color already).

Maybe by adding 2 optional props for line width and circle width and height.

This is what I have:
![image](https://user-images.githubusercontent.com/3510343/132450850-75a217c4-0579-4e3f-88da-3df005c7d317.png)

and this is what I am trying to achieve:
![image](https://user-images.githubusercontent.com/3510343/132450635-144ce815-995d-4126-9b88-957798709da7.png)

Thanks!

**Comment by dogfootruler-kr** [comment]
For the moment I just override the css like:
```css
const useStyles = makeStyles(() =>
  createStyles({
    root: {
      '& div[data-testid="tree-leaf-click"] > div': {
        width: '.5rem',
        height: '.5rem',
      },
      '& div[data-testid="tree-leaf"]': {
        '&::after': {
          width: '2px',
        },
      },
      '& #timeline-main-wrapper': {
        '&::-webkit-scrollbar-thumb': {
          backgroundColor: '#dbdbdb',
          outline: '1px solid #dbdbdb',
        },
      },
    },
  })
);
```
