### ISSUE TITLE
The abnormal box model causes the overall style to be skewed to the right

### ISSUE THREAD

**Issue by bigbigDreamer** [prabhuignoto/react-chrono#269]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/39019913/180598485-6ca752b4-781a-450a-9df8-c3cda5187f2a.png">

When I change the box model of the DOM element it looks back to normal～

add as follow：

```css
xxx: {
   box-sizing: border-box;
}
```

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/39019913/180598571-f0f971a2-40c7-4064-aecc-acf592bf3332.png">

**Comment by bigbigDreamer** [comment]
Can I propose a PR to fix this @prabhuignoto , roughly the following changes：

```css
*, :after,  :before {
     box-sizing: border-box;
}
```

I think it's necessary to turn on the layout box for **any element** to be `border-box`, so that you can avoid a lot of `css traps`
